spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/hanyh_032/spring-cloud.git
          search-paths: respo
          username: 253029790@qq.com
          password: 123qwertyuiop

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/